=== filedos9ig1d/kendzi0/kendzi.josm.plugin3d/resources/xsd/TextureLibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.kendzi3d.org"
	xmlns="http://www.kendzi3d.org"
	
	elementFormDefault="unqualified"
	>
<!--     xmlns:jxb="http://java.sun.com/xml/ns/jaxb" -->
<!--     jxb:version="2.0"> -->

			
	<xs:element name="textureLibrary" type="TextureLibrary"/>
	
	<xs:complexType name="TextureLibrary">		
		<xs:sequence>
    		<xs:element name="textureSet" type="TextureSet" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>
    	<xs:attribute name="author" type="xs:string" use="optional"/>
	</xs:complexType>
	
	
	<xs:complexType name="TextureSet">			
		<xs:sequence>
    		<xs:element name="textureData" type="TextureData" minOccurs="0" maxOccurs="unbounded"/>
    	</xs:sequence>		
		<xs:attribute name="key" type="xs:string"/>	
	</xs:complexType>
	
	<xs:complexType name="TextureData">
	
		<xs:attribute name="fileKey" type="xs:string"/>
		
		<xs:attribute name="height" type="xs:double"/>
		<xs:attribute name="width" type="xs:double"/>
  
    </xs:complexType>
</xs:schema>

=== filedos9ig1d/kendzi0/kendzi.josm.plugin3d/colorTextureLibrary.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:textureLibrary 
	xmlns:ns2="http://www.kendzi3d.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kendzi3d.org xsd/TextureLibrary.xsd"
	
	author="Tomasz KÄ™dziora (Kendzi)"
	>
<!-- 	xmlns="http://www.kendzi3d.org"  -->
<!-- 	<ns2:textureLibrary xmlns:ns2="http://www.kendzi3d.org"> -->
	
	
	<!-- Buildings -->
	<textureSet key="buildings.facade_unknown">
		<textureData fileKey="#c=0xffe68c" height="1.0" width="1.0"/>
	</textureSet>
	<textureSet key="buildings.facade_plaster">
		<textureData fileKey="#c=0xffe68c" height="1.0" width="1.0"/>
	</textureSet>
	<textureSet key="buildings.facade_brick">
		<textureData fileKey="#c=0xffe68c" height="1.0" width="1.0"/>
	</textureSet>
	<textureSet key="buildings.facade_stone">
		<textureData fileKey="#c=0xffe68c" height="1.0" width="1.0"/>
	</textureSet>
	 
	<!-- Roof -->
	<textureSet key="buildings.roof_unknown">
		<textureData fileKey="#c=0xcd0000" height="1.0" width="1.0"/>
	</textureSet>
	<textureSet key="buildings.roof_roofTiles">
		<textureData fileKey="#c=0xcd0000" height="1.0" width="1.0"/>
	</textureSet>
	<textureSet key="buildings.roof_roofingFelt">
		<textureData fileKey="#c=0xcd0000" height="1.0" width="1.0"/>
	</textureSet>
	
	<textureSet key="buildings.window">	
		<textureData fileKey="#c=0xcf0f0f0" height="1" width="1"/>
	</textureSet>
	
	<!-- Barrier -->
	<textureSet key="barrier.fence_unknown">
		<textureData fileKey="#c=0xcf0f0f0" height="1" width="1"/>
	</textureSet>
	<textureSet key="barrier.fence_balustrade">
		<textureData fileKey="#c=0xcf0f0f0" height="1" width="1"/>
	</textureSet>


</ns2:textureLibrary>

=== filedos9ig1d/kendzi0/kendzi.josm.plugin3d/resources/textureLibraryInternal.xml
<?xml version="1.0" encoding="UTF-8"?>
<textureLibrary 
	xmlns="http://www.kendzi3d.org" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.kendzi3d.org xsd/TextureLibrary.xsd"
	
	author="Tomasz KÄ™dziora (Kendzi)"
	>
	
	
	<!-- Buildings -->
	<textureSet key="buildings.facade_unknown">
		<textureData fileKey="/textures/building_facade_unknown.png" height="2.0" width="2.0"/>
	</textureSet>
	<textureSet key="buildings.facade_plaster">
		<textureData fileKey="/textures/building_facade_plaster.png" height="2.0" width="2.0"/>
	</textureSet>
	<textureSet key="buildings.facade_brick">
		<textureData fileKey="/textures/building_facade_brick.png" height="0.3" width="0.5"/>
		<textureData fileKey="/textures/pd/MarekSeamlessBrick001.jpg" height="0.42" width="0.5"/>
		<textureData fileKey="/textures/pd/MarekBrick002.jpg" height="0.5" width="0.5"/>
		<textureData fileKey="/textures/pd/MarekSeamlessBrick003.jpg" height="0.5" width="0.5"/>
		<textureData fileKey="/textures/pd/brick_large2.png" height="1.8" width="2.75"/>
	</textureSet>
	<textureSet key="buildings.facade_stone">
		<textureData fileKey="/textures/pd/Red_sandstone_wall.jpg" height="1.8" width="1.8"/>
	</textureSet>
	 
	<!-- Roof -->
	<textureSet key="buildings.roof_unknown">
		<textureData fileKey="/textures/building_roof_material_unknown.png" height="2" width="2"/>
	</textureSet>
	<textureSet key="buildings.roof_roofTiles">
		<textureData fileKey="/textures/building_roof_material_roofTiles.png" height="3" width="3"/>
	</textureSet>
	<textureSet key="buildings.roof_roofingFelt">
		<textureData fileKey="/textures/building_roof_material_roofingFelt.png" height="2" width="2"/>
	</textureSet>
	
	<!-- Barrier -->
	<textureSet key="barrier.fence_unknown">
		<textureData fileKey="/textures/fence_undefined.png" width="2"/>
	</textureSet>
	<textureSet key="barrier.fence_balustrade">
		<textureData fileKey="/textures/fence_balustrade.png" width="0.2"/>
	</textureSet>


</textureLibrary>
